---
kind: pipeline
type: docker
name: rubytalks

steps:
  - name: rubocop
    image: ruby:2.6.3
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rubocop

  - name: rspec
    image: ruby:2.6.3
    volumes:
      - name: bundle
        path: /usr/local/bundle
    commands:
      - gem install bundler
      - bundle install
      - HANAMI_ENV=test bundle exec rake db:migrate
      - bundle exec rspec

  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TG_TOKEN
      to:
        from_secret: TG_USER_ID
      socks5:
        from_secret: SOCKS5
    when:
      status:
        - success
        - failure

services:
  - name: postgres
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rubytalks_test

  - name: redis
    image: redis:5.0-alpine

volumes:
  - name: bundle
    temp: {}
