image: "registry.gitlab.com/kova1/rubytalks:latest"

services:
  - postgres:9.6.3
  - redis:latest

variables:
  LC_ALL: C.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  TZ: Europe/Moscow
  HANAMI_ENV: test
  DATABASE_URL: 'postgresql://postgres:postgres@postgres/rubytalks_test'
  REDIS_HOST: redis
  REDIS_PORT: 6379

.default-cache:
  cache:
    untracked: true
    key: CACHE-KEY-5.1
    paths:
      - vendor/
      - public/

stages:
  - build
  - prepare
  - deploy

build:
  extends: .default-cache
  stage: build
  script:
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec hanami db prepare

rubocop:
  extends: .default-cache
  stage: prepare
  script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec rubocop

rspec:
  extends: .default-cache
  stage: prepare
  script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec hanami db prepare
    - bundle exec rspec spec
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

# TODO: fix deploy to heroku
deploy:
  stage: deploy
  when: manual
  script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y heroku-toolbelt
    - gem install dpl
    - dpl --provider=heroku --app=morning-scrubland-21434 --api-key=$HEROKU_API_KEY
