version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        PG_MAJOR: '11'
        BUNDLER_VERSION: '2.1.2'
        USER_ID: 1000
        GROUP_ID: 1000
    image: rubytalks-dev:1.0.0
    tmpfs:
      - /tmp

  web: &web
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - hanami_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - .dockerdev/.bash_aliases:/home/user/.bash_aliases
    environment:
      - HANAMI_ENV=${HANAMI_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
    depends_on:
      - postgres
      - redis

  runner:
    <<: *web
    container_name: runner
    command: /bin/bash
    ports:
      - '2300:2300'

  hanami:
    <<: *web
    container_name: hanami
    command: bundle exec hanami s --host=0.0.0.0
    ports:
      - '2300:2300'

  sidekiq:
    <<: *web
    container_name: sidekiq
    command: bundle exec sidekiq -r ./config/boot.rb -c 7

  postgres:
    container_name: postgres
    image: postgres:11.1
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432

  redis:
    container_name: redis
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  postgres:
  redis:
  bundle:
  hanami_cache:
