version: 2.1
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/ruby:2.6.3 # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          HANAMI_ENV: test
          DATABASE_URL: postgresql://localhost/rubytalks_test
          REDISTOGO_URL: redis://localhost:6379

      - image: circleci/postgres:11 # database image
        environment: # environment variables for database
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rubytalks_test
          POSTGRES_PASSWORD: ""

      - image: circleci/redis:5.0.3
    steps:
      - checkout
      - run:
          name: Install postgres client
          command: |
            sudo apt update
            sudo apt install postgresql-client

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache for Ruby dependencies if available
      - restore_cache:
          keys:
            - rubytalks-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rubytalks-bundle-v2-
      # Install Ruby dependencies
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: rubytalks-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec hanami db prepare
      # RSpec
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec
      - run:
          name: Run rubocop
          command: |
            bundle exec rubocop
